create table member
(
    id            bigint generated by default as identity primary key,
    role          varchar(20) not null,
    nickname      varchar(20) not null,
    main_badge_id bigint,
    created_at    timestamp(6) with time zone,
    updated_at    timestamp(6) with time zone
);

create table badge
(
    id             bigint generated by default as identity primary key,
    name           varchar(20)  not null,
    type           varchar(20)  not null,
    required_value integer      not null,
    description    varchar(100) not null,
    image_path     varchar(255) not null
);

create table badge_achievement
(
    id         bigint generated by default as identity primary key,
    badge_id   bigint not null,
    member_id  bigint not null
        constraint fk_badge_achievement_member references member,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone
);

create table level
(
    id              bigint generated by default as identity primary key,
    exp_range_start integer not null,
    exp_range_end   integer not null
);

create table member_level
(
    id         bigint generated by default as identity primary key,
    exp        integer not null,
    level_id   bigint  not null,
    member_id  bigint  not null
        constraint uk_member_level_member unique
        constraint fk_member_level_level references member_level references member,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone
);

create table social_profile
(
    id          bigint generated by default as identity primary key,
    member_id   bigint       not null
        constraint fk_social_profile_member references member,
    social_type varchar(20)  not null,
    oauth_id    varchar(255) not null,
    oauth_email varchar(255) not null,
    created_at  timestamp(6) with time zone,
    updated_at  timestamp(6) with time zone
);

create table running_record
(
    id               bigint generated by default as identity primary key,
    member_id        bigint                      not null
        constraint fk_running_record_member references member,
    average_pace     double precision            not null,
    calorie          double precision            not null,
    distance_meter   integer                     not null,
    duration_seconds integer                     not null,
    emoji            varchar(20)                 not null,
    location         varchar(255)                not null,
    route            geometry(LineString, 4326),
    start_at         timestamp(6) with time zone not null,
    end_at           timestamp(6) with time zone not null,
    created_at       timestamp(6) with time zone,
    updated_at       timestamp(6) with time zone
);

create table scale
(
    id         bigint generated by default as identity primary key,
    name       varchar(255) not null,
    size_meter integer      not null
);
