-- crate challenge table
CREATE TABLE challenge
(
    id              bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar NOT NULL,
    expected_time   integer NOT NULL,
    challenge_type  varchar(100) NOT NULL,
    image_url       varchar NOT NULL
);

-- crate challenge_goal_condition table
CREATE TABLE challenge_goal_condition
(
    id                  bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    challenge_id        bigint  NOT NULL
        CONSTRAINT fk_challenge_goal_condition_challenge_id REFERENCES challenge,
    goal_type           varchar(100) NOT NULL,
    goal_value          integer NOT NULL,
    comparison_type     varchar(100) NOT NULL
);
