-- drop columns in challenge_achievement table
ALTER TABLE challenge_achievement
    DROP COLUMN has_percentage,
    DROP COLUMN start_value,
    DROP COLUMN end_value,
    DROP COLUMN achievement_value,
    DROP COLUMN percentage;

-- crate challenge_achievement_percentage
CREATE TABLE challenge_achievement_percentage
(
    id                              bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    challenge_achievement_id        bigint  NOT NULL
        CONSTRAINT uk_challenge_achievement_percentage_challenge_achievement_id UNIQUE
        CONSTRAINT fk_challenge_achievement_percentage_challenge_achievement_id REFERENCES challenge_achievement,
    start_value         integer NOT NULL,
    end_value           integer NOT NULL,
    achievement_value   integer NOT NULL,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone
);
